// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYjtyDv7H9QGj_HiIjT0V0Je7oCtIOOxM',
    appId: '1:665593628324:web:fe8730fa8cb7e484e54831',
    messagingSenderId: '665593628324',
    projectId: 'mentalhealth-bf2be',
    authDomain: 'mentalhealth-bf2be.firebaseapp.com',
    storageBucket: 'mentalhealth-bf2be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIwXi7SkE9vqhETjy-tZqP9RvCr1WHXe8',
    appId: '1:665593628324:android:db9bfbc88e970239e54831',
    messagingSenderId: '665593628324',
    projectId: 'mentalhealth-bf2be',
    storageBucket: 'mentalhealth-bf2be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvwal8QiPcc-dTFKtVLxeDc8RScDiS_Os',
    appId: '1:665593628324:ios:f85aa433f92dec77e54831',
    messagingSenderId: '665593628324',
    projectId: 'mentalhealth-bf2be',
    storageBucket: 'mentalhealth-bf2be.appspot.com',
    iosBundleId: 'com.example.mentalhealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvwal8QiPcc-dTFKtVLxeDc8RScDiS_Os',
    appId: '1:665593628324:ios:f85aa433f92dec77e54831',
    messagingSenderId: '665593628324',
    projectId: 'mentalhealth-bf2be',
    storageBucket: 'mentalhealth-bf2be.appspot.com',
    iosBundleId: 'com.example.mentalhealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYjtyDv7H9QGj_HiIjT0V0Je7oCtIOOxM',
    appId: '1:665593628324:web:921be7161300f3b9e54831',
    messagingSenderId: '665593628324',
    projectId: 'mentalhealth-bf2be',
    authDomain: 'mentalhealth-bf2be.firebaseapp.com',
    storageBucket: 'mentalhealth-bf2be.appspot.com',
  );
}
