// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvLPGKk9Es-0T2nbpYkqlbRt9nx6qQ8ds',
    appId: '1:255154726162:web:dbbde12cc202939545ffcb',
    messagingSenderId: '255154726162',
    projectId: 'wellcarebot-71cca',
    authDomain: 'wellcarebot-71cca.firebaseapp.com',
    storageBucket: 'wellcarebot-71cca.appspot.com',
    measurementId: 'G-6212Y71PBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI-RKncZnhXIzHKnOKbW54o0FZlI_2OKM',
    appId: '1:255154726162:android:848e5bd49c06ba1245ffcb',
    messagingSenderId: '255154726162',
    projectId: 'wellcarebot-71cca',
    storageBucket: 'wellcarebot-71cca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsAGvLJQ2Hrjgj0K35TXz_3uyEqZXKBJI',
    appId: '1:255154726162:ios:1f19d23d9db3cd6845ffcb',
    messagingSenderId: '255154726162',
    projectId: 'wellcarebot-71cca',
    storageBucket: 'wellcarebot-71cca.appspot.com',
    iosBundleId: 'com.example.mentalhealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsAGvLJQ2Hrjgj0K35TXz_3uyEqZXKBJI',
    appId: '1:255154726162:ios:1f19d23d9db3cd6845ffcb',
    messagingSenderId: '255154726162',
    projectId: 'wellcarebot-71cca',
    storageBucket: 'wellcarebot-71cca.appspot.com',
    iosBundleId: 'com.example.mentalhealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvLPGKk9Es-0T2nbpYkqlbRt9nx6qQ8ds',
    appId: '1:255154726162:web:3dcb1e81700addba45ffcb',
    messagingSenderId: '255154726162',
    projectId: 'wellcarebot-71cca',
    authDomain: 'wellcarebot-71cca.firebaseapp.com',
    storageBucket: 'wellcarebot-71cca.appspot.com',
    measurementId: 'G-M0Z4FVGXFV',
  );
}
